### PR TITLE
Added instructions for Create React App (CRA)

### PR DESCRIPTION
**Pull request by mrnmilutinovic**
Based on this conversation https://github.com/GillianPerard/typescript-json-serializer/issues/132
I added instructions on how to use this with CRA.

### CODE REVIEW

**Comment by GillianPerard** [comment]
Hi, thank you for the PR!

I've to test the usecase and I've some modifications to apply to your commit, so do you prefer I take your changes and I update it or would you like to do all the remarks?

**Comment by mrnmilutinovic** [comment]
@GillianPerard 

Thanks for the review. 
Whatever works for you. I can make the changes if necessary.

**Comment by GillianPerard** [comment]
Hi, I tried your example and it does not work for me...

I also try to implement a solution with more used pakcages than `craco`. It works for me in development mode but fails on in production if I use `@JsonProperty` directly inside the `constructor` but works well for other cases.
I'm currently searching a solution, I found that the problem come from my function to parse the `constructor` that does not handle the specific format generated by `React`.

**Comment by mrnmilutinovic** [comment]
I will be able to take a look at what you have over the weekend if you are open to it. 
Also I might do a fresh installation of CRA and try to replicate issues you are encountering.

**Comment by GillianPerard** [comment]
Thank you for your help, I fixed the problem, I created a new PR #144,  could you check if everything is good for you then I'll merge 😊.

**Pull request closed without merging**
