### PR TITLE
add function prototype for property

### PR DESCRIPTION
**Pull request by sco974**
Hello 
here is a lite addition allow user to better see the prototype of serializes, predicate function in decorated property.
is it of interest for you ? let me know what you think please
Thanks

### CODE REVIEW

**Comment by GillianPerard** [comment]
Hi, yes it could be great, let me check a better naming and push it 😊, thanks!

**Comment by sco974** [comment]
Ok :-)

**Comment by GillianPerard** [comment]
Hi, sorry to be late, but I just add your proposition to the new 2.4.1 version 😊 Thank you again!

**Comment by sco974** [comment]
No prob at all
You’re welcome thanks for this good lib :-)

**Pull request closed without merging**
